# Generated by Django 6.0.5 on 2026-05-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(choices=[('gray', 'Red'), ('black', 'Black'), ('cream', 'Cream'), ('navy', 'Navy'), ('white', 'White')], max_length=15)),
                ('screen_size', models.DecimalField(choices=[(11.6, 11.6), (12, 12), (13.3, 13.3), (14, 14), (15.6, 15.6), (16, 16), (17.3, 17.3)], decimal_places=1, max_digits=3)),
                ('features', models.CharField(max_length=500)),
            ],
        ),
    ]
