# Generated by Django 6.0.5 on 2026-05-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, default='default_computer.png', upload_to='computers/'),
        ),
    ]
