# Generated by Django 6.0.5 on 2026-05-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_computer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, default='default_computer.jpg', upload_to='computers/'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='screen_size',
            field=models.CharField(choices=[('11.6', '11.6'), ('12', '12'), ('13.3', '13.3'), ('14', '14'), ('15.6', '15.6'), ('16', '16'), ('17.3', '17.3')], max_length=5),
        ),
    ]
